# Generated by Django 3.2.4 on 2023-01-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20230121_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='foods',
            field=models.ManyToManyField(to='cart.CartFood'),
        ),
    ]
