# Generated by Django 3.2.4 on 2023-01-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
